version: '3'
services:
  server-jrpc:
    container_name: bookstore_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8800:8800
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      -     bookstoregrpc-mysql
    networks:
      - fullstack

  client-jrpc:
    container_name: bookstore_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    networks:
      - fullstack


  bookstoregrpc-mysql:
    image: mysql:latest
    container_name: bookstore_db_mysqlgRPC
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_HOST=bookstore-mysql
      - MYSQL_USER=pavel
      - MYSQL_PASSWORD=mysqlpaha100688
      - MYSQL_DATABASE=testdb2
      - MYSQL_ROOT_PASSWORD=mysqlpaha100688
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack



volumes:
  api:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge